server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      user.name: admin
      user.password: admin

      
logging:
  level:
    root: INFO
 
greeting:
  message: Hello And NAtalia
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
